### ISSUE TITLE
能增加一个0.96寸oled位置吗

### ISSUE THREAD

**Issue by FantasyGmm** [leipopo/kekeandzuozuo4rock5b#1]
能不能加个0.9寸长条oled的屏位置啊，可以显示一些信息，程序方便等我板子到手了我可以写一个
用蓝图风扇噪音大不大啊，之前买过动平衡很差，噪音很大，直接丢了

**Comment by leipopo** [comment]
屏幕等我淘宝一下看看具体尺寸，应该也许能加但是线肯定不会太好走。鹏达蓝图的低转速3010不太行，要静音的话换一家吧。（我又买了12k转的过两天到了试试

**Comment by leipopo** [comment]
能加但是线不会太好走。鹏达蓝图的低转速3010不太行，要静音的话就换一家吧。（我又买了12k转的过两天到了试试

**Comment by leipopo** [comment]
我试试在上盖加一个，应该问题不大。

**Comment by FantasyGmm** [comment]
4010风扇可以买建准的磁悬浮 声音挺小的 就是风力有点小

**Comment by leipopo** [comment]
4010稍微大了点，而且风道要做收口不太好搞

**Comment by FantasyGmm** [comment]
这个风道有用吗，我看这四周孔挺多的，风不会走其他地方漏出去吗

**Comment by FantasyGmm** [comment]
用的是普通直吹风扇，还是涡轮扇侧出风的

**Comment by FantasyGmm** [comment]
看了下文件，感觉可以把字取消了，然后风扇换成4010，正好旁边加一个长条的oled

**Comment by leipopo** [comment]
![image](https://user-images.githubusercontent.com/53897646/190947473-c54108e9-6a61-4e3c-a762-f4efb7161081.png)

4010稍微太大了点。。oled已经扣出来了明天到了测一测

**Comment by leipopo** [comment]
我准备做个5b的散热座，60/90的大风扇从下吹风给ssd和整个pcb散热，然后在那个座子上开这个屏幕口子，就先关掉这个issue了

**Comment by FantasyGmm** [comment]
> 我准备做个5b的散热座，60/90的大风扇从下吹风给ssd和整个pcb散热，然后在那个座子上开这个屏幕口子，就先关掉这个issue了

好，等大佬了，顺便做高个树莓派冰塔下压兼容的，盖板吧
